jenkinsci/workflow-multibranch-plugin

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/NoTriggerBranchPropertyWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Integration test for https://github.com/jenkinsci/branch-api-plugin/pull/43. Pending https://github.com/jenkinsci/branch-api-plugin/pull/36, fixes a bug whereby changes to the trigger settings on a (single-repository) multibranch project would not take effect on branch projects that had already been created. (Organization folders did not suffer from an analogous bug.)
Supersedes https://github.com/jenkinsci/workflow-multibranch-plugin/pull/2.
@reviewbybees

[JENKINS-30206] [JENKINS-32396] Honor changes to NoTriggerBranchProperty

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

Related to https://github.com/jenkinsci/workflow-scm-step-plugin/pull/4.
@reviewbybees

Removing Mercurial-specific tests

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

Note that there is a trivial merge conflict with #17. The corresponding case does _not_ currently pass for Mercurial; under investigation.
@reviewbybees

Demonstrate that changelogs are computed for noninitial builds of Git and Subversion branch projects

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

[JENKINS-34005](https://issues.jenkins-ci.org/browse/JENKINS-34005)
Depends on https://github.com/jenkinsci/workflow-job-plugin/pull/9
* Updates existing tests to deal with the fact that there should always be a `PipelineTriggersJobProperty` on a `WorkflowJob`, even if it has no triggers in it.
* Added a new test specifically for `PipelineTriggersJobProperty`.
cc @reviewbybees esp @jglick

JENKINS-34005 - update tests for PipelineTriggersJobProperty

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

[JENKINS-37731](https://issues.jenkins-ci.org/browse/JENKINS-37731)
Note that we're pretty much stuck with SCMTrigger not working right
with the snippet generator pre-core-2.21 (or whenever
https://github.com/jenkinsci/jenkins/pull/2526 lands). SCMTrigger is
just busted vis a vis the Snippet Generator. So what we're doing here
is testing runtime syntax, and snippet generation against core with a
new enough version to have the "pollScm" symbol on SCMTrigger's descriptor.
Also enabled/fixed some snippetizer round trip tests that now can
work, while I was here.
cc @reviewbybees esp @jglick @daniel-beck

[JENKINS-37731] Tests for proper handling of SCMTrigger in step.

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

After https://github.com/jenkinsci/workflow-cps-plugin/pull/60 + https://github.com/jenkinsci/workflow-job-plugin/pull/24 build parameters come in principally as environment variables, rather than as entries in the Groovy `[Script.]binding`; *defined* parameters can still be accessed as if they were in the binding, due to the fallback to `env`, but `binding` itself does not list them.
That means the original hack for using `ParametersDefinitionProperty` from a multibranch `Jenkinsfile` no longer works. The variant here works with or without those updates; the commented-out syntax is the intended usage going forward (and one of the motivations for making these changes to begin with).
@reviewbybees esp. @abayer

Adapting test to run with or without parameter behavior updates

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

Seems to fail on CI, though it passes for me locally; switching to SVNKit, which should insulate the test from unpredictable CLI versions.
@reviewbybees

SCMBinderTest.exactRevisionSubversion failure

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-33273](https://issues.jenkins-ci.org/browse/JENKINS-33273)
Tests take advantage of https://github.com/jenkinsci/git-plugin/pull/455.
@reviewbybees esp. @stephenc

[JENKINS-33273] Use SCMFileSystem where available

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java

Amends #49 to allow people to disable the new functionality without downgrading, if there is some kind of problem. Cf. https://github.com/jenkinsci/workflow-cps-plugin/pull/97 where there is a UI option.
@reviewbybees

SCMFileSystem kill switch

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java

Part of [JENKINS-42817](https://issues.jenkins-ci.org/browse/JENKINS-42817).
@reviewbybees

[JENKINS-42817] readTrusted broke with CpsScmFlowDefinition & heavyweight checkouts

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java

[JENKINS-50784](https://issues.jenkins-ci.org/browse/JENKINS-50784) - will fix minor regressions in cases where the execution of the previous build is not lazy-loaded c.f. https://github.com/jenkinsci/workflow-job-plugin/pull/93

Fix [JENKINS-50784] by using a blocking load of execution where needed

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

... unfortunately we may legitimately null the execution for certain critical failures.
[https://issues.jenkins-ci.org/browse/JENKINS-51290](https://issues.jenkins-ci.org/browse/JENKINS-51290)
@reviewbybees 
Note: A *better* fix would be to add a new API to `FlowExecutionOwner` that can trigger lazy loading and behaves like either `FlowExcecutionOwner#get()` or `FlowExcecutionOwner#getOrNull()` but this issue is fairly critical so we need at least a fast solution.

Test and fix for [JENKINS-51290] - properties step fails with error about job not yet started if could not obtain execution for previous run

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

This pull request updates unit tests in workflow-multibranch so that they are compatible with versions of git-plugin >=3.9.0. These changes to git-plugin went in with [PR 577](https://github.com/jenkinsci/git-plugin/pull/577). As such, there is now a test-scope maven dependency for git-plugin 3.9.1. `git-plugin.version` has been left at 3.7.0.
@svanoort and @rsandell , your reviews would be appreciated. Thanks!

Update unit tests for compatibility with git-plugin >=3.9.x

---

.mvn/extensions.xml
.mvn/maven.config
Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java

Subsumes #81. Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/129 and https://github.com/jenkinsci/jenkins-test-harness/pull/113. Amends #33.

[JENKINS-2111] Integration test of new workspace naming strategy

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Companion PR to core change https://github.com/jenkinsci/jenkins/pull/3014
Built against https://github.com/jenkinsci/jenkins/pull/3014/commits/7b8e4b1e093550dc8ca1f3664ed161e9c24a93db

[JENKINS-26143] Tests

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Subsumes #72 and serves as a testbed for [JENKINS-53917](https://issues.jenkins-ci.org/browse/JENKINS-53917).

[JENKINS-26143] [JENKINS-53917] Integration testing of ChoiceParameterDefinition

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

https://github.com/jenkinsci/ssh-slaves-plugin/pull/79 and the like are pretty annoying: the historical behavior of `SCMBinder` is to allow a build which includes an untrusted edit to `Jenkinsfile` to proceed, but actually reading the `Jenkinsfile` contents from the corresponding trusted revision instead. If you get a green check mark, no one is going to go looking for the one-line warning about this. It is better to behave as if the script started with
```groovy
readTrusted 'Jenkinsfile'
```
In other words, to just fail immediately in such a case. I cannot think of any good reason for anyone to be relying on the old behavior, but just in case I kept it as an option which can be enabled by system property.
Note that this change will not have any effect on GitHub PR merge jobs until …

Make SCMBinder try to abort builds in which Jenkinsfile has been modified by an untrusted contributor

---

pom.xml

Observed in jenkinsci/bom#53 when attempting to add `workflow-multibranch` to the  managed set. Running the Plugin Compatibility Tester against `workflow-multibranch` plugin and a newer version of `workflow-scm-step`, the following error appears:
> Failed to execute goal on project workflow-multibranch: Could not resolve dependencies for project org.jenkins-ci.plugins.workflow:workflow-multibranch:hpi:2.21: Could not find artifact org.jenkins-ci.plugins.workflow:workflow-scm-step:jar:tests:2.9 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]
I saw that between `workflow-scm-step` [2.6](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/workflow/workflow-scm-step/2.6/) and [2.7](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/workflow/workflow-sc …

Upgrade workflow-scm-step past 2.6

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReplayActionTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java

While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`ACL.impersonate(org.acegisecurity.Authentication, java.lang.Runnable)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-java.lang.Runnable-) states: "use try with resources and [`as(Authentication)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#as-org.acegisecurity.Authentication-)".
- The documentation for [`User.get(java.lang.String)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#get-java.lang.String-) states: "This method is deprecated, because it causes unexpected `User` creation by API usage code and causes performance degradation of used to retrieve users by ID. Use [`getById(java.lang.String, …

Remove usages of deprecated APIs

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Had this on the back burner waiting for https://github.com/jenkinsci/bom/pull/264 and https://github.com/jenkinsci/bom/pull/278 to make it into a release, but going ahead and filing it now so we can release `workflow-multibranch` to unblock https://github.com/jenkinsci/bom/pull/280.

Update minimum core version, parent POM, and dependencies

---

pom.xml

Missed one plugin, doing this instead of #106 .

Move matrix-auth to bom version

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Due to jenkinsci/jenkins#5275 a test breaks PCT and is blocking jenkinsci/bom#511.
Adapt the test to work for the plugin's version of jenkins and for the later releases of jenkins
Tested manually with `mvn clean install -Djenkins.version=2.289`

Add description in test to prevent PCT failure in newer Jenkins versions

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

See jenkinsci/bom#471 and jenkinsci/bom#472. These PRs are attempting to add new plugins to the BOM, which trip up `JobPropertyStepTest#configRoundTripBuildDiscarder`. `JobPropertyStepTest#configRoundTripBuildDiscarder` expects to see exactly one job property after round-tripping the configuration. But when those other two plugins are on the classpath, round-tripping has three job properties:
```
0 = {BuildDiscarderProperty@11636}
1 = {RebuildSettings@11637}
2 = {ThrottleJobProperty@11638}
```
This PR simply loosens the test to allow for additional job properties to be present. This allows PCT to pass when Rebuild and Throttle Concurrent Builds are also on the classpath.

Loosening `JobPropertyStepTest#configRoundTripBuildDiscarder`.

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Proof that even when defining parameters via the `properties` step on an initial build of a project, the fix of SECURITY-170 only blocks access to parameters as environment variables. They can always be accessed via the `params` map (since that poses no Shellshock risk).

Added `JobPropertyStepTest.triggerWithParameter`

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

#128 patched one test for `bom` PCT but neglected to do the same for a similar test. Fixes https://github.com/jenkinsci/bom/issues/811.

Extend PCT fix to `JobPropertyStepTest.configRoundTripParameters`

---

pom.xml

Amends #180 via https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/5 to try to solve a build error in https://github.com/jenkinsci/bom/pull/1168.

Backdate core dep from 2.303.x to 2.289.x

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

The WorkflowMultiBranchProject class does not have a proper Symbol in the descriptor as many other such as FreeStyleProject (https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/FreeStyleProject.java#L79)

Adding symbol to the WorkflowMultiBranchProject class descriptor

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

https://issues.jenkins.io/browse/JENKINS-70680

[JENKINS-70680] Reproducing issue with `properties` + `parameters` + `defaultValue`

---

pom.xml
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/getting-started-links.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/getting-started-links.jelly

The change proposed adapts the standard Jenkins icons (ionicons) used in core itself. In this case, the icons look most the same, but ionicons support our theme-ability API and are recommended to use.

Adapt standard Jenkins icons

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java

Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.

Forward compatibility with Guice 7

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Downstream of https://github.com/jenkinsci/jenkins/pull/8902 & https://github.com/jenkinsci/cloudbees-folder-plugin/pull/367.

[JENKINS-72613] Demonstrating bug & fix in test

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java

Follow up to @mawinter69 changes in core (https://github.com/jenkinsci/jenkins/pull/9127). This PR uses the branch symbol now that the 'New item' page supports displaying them.
**Before**
**After**
* Branch symbol displays as expected in the 'New item' page
```[tasklist]
```

Use symbol for multi branch pipeline icon

---

pom.xml

align to LTS and pickup bom with fixed subversion
when running tests with PCT and a newer git-client issues with subversion are found as it can not resolve trilead classes.
the version of subversion-plugin used but did not declare a dependency on trilead, so this fixes the issue by update the bom to pickup https://github.com/jenkinsci/subversion-plugin/releases/tag/1256.vee91953217b_6
@jglick @olamy

update bom to pickup fixed subversion for tests

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

https://github.com/jenkinsci/workflow-multibranch-plugin/pull/238#pullrequestreview-1829735278, akin to #17. Note also baseline cleanup after #304.

Remove `subversion` test dep

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMVarTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java

Migrate from deprecated functionality to non-deprecated equivalents.
`mvn clean verify`

Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowBranchProjectFactory.java

Testing with
```java
diff --git a/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java b/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
index 86d2af8..501a484 100644
--- a/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
+++ b/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
@@ -233,7 +233,7 @@ public class WorkflowMultiBranchProjectTest {
@Test public void configuredScriptNameBranches() throws Exception {
sampleRepo.init();
-        WorkflowMultiBranchProject mp = r.jenkins.createProject(WorkflowMultiBranchProject.class, "p");
+        WorkflowMultiBranchProject mp = …
```

Avoid need for `idealNames` workaround

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java

Migrate from deprecated/EOL Commons Lang 2 to native Java Platform functionality.

Replace `StringUtils` with native Java Platform equivalents

---

src/main/resources/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchProperty/config.jelly

Use consistent style for pipeline branch speed dropdown
**Before**
**After**

Update inconsistent style for pipeline branch speed dropdown
