src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java

[JENKINS-34235](https://issues.jenkins-ci.org/browse/JENKINS-34235)
@reviewbybees especially @amuniz

[JENKINS-34235] Wrong plugin short-name in the URL pattern

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Useful to validate https://github.com/jenkinsci/git-plugin/pull/400 & https://github.com/jenkinsci/branch-api-plugin/pull/40.
@reviewbybees

Dump branch project indexing to test log

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMBinder/config.jelly

Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/12.
@reviewbybees

[JENKINS-31831] Show Pipeline Groovy link on multibranch projects

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowMultiBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Refactored to allow alternate implementations besides fixed Jenkinsfile

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep/help-path.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep/help.html
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-34596](https://issues.jenkins-ci.org/browse/JENKINS-34596)
@reviewbybees

[JENKINS-34596] Added readTrusted step

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

Forgotten in #11.
@reviewbybees

Add some useful things from SCMBinderTest to the test JAR

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowMultiBranchProjectFactory.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java

Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/45.
@reviewbybees

[JENKINS-34246] Make AbstractWorkflowMultiBranchProjectFactory handle deletion or update of existing children

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep/help.html
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java

Sort of a marriage between [JENKINS-31386](https://issues.jenkins-ci.org/browse/JENKINS-31386) and #10 ([JENKINS-34596](https://issues.jenkins-ci.org/browse/JENKINS-34596)).
@reviewbybees

[JENKINS-31386] [JENKINS-34596] Allow readTrusted to work from CpsScmFlowDefinition

---

pom.xml

Bump parent POM to fix PCT against new cores.

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java

Analogous to https://github.com/JFrogDev/jenkins-artifactory-plugin/pull/30. Might alleviate the symptom of a bug perhaps caused by https://github.com/jenkinsci/workflow-cps-plugin/pull/42.
@reviewbybees

[JENKINS-37538] Should use AbstractSynchronousNonBlockingStepExecution

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

[JENKINS-37219](https://issues.jenkins-ci.org/browse/JENKINS-37219)
Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/48
cc @reviewbybees esp @jglick

[JENKINS-37219] Test for new overrideIndexTriggers job property.

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Depends on https://github.com/jenkinsci/workflow-job-plugin/pull/17, which I can't deploy a SNAPSHOT of due to changes in Artifactory permissions.
cc @reviewbybees esp @jglick

Test for JENKINS-37477

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Just wanted to make sure we had this and working correctly.
cc @reviewbybees esp @jglick

Adding a test of an empty triggers property removing triggers.

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReplayActionTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMVarTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Downstream of https://github.com/jenkinsci/script-security-plugin/pull/82.
@reviewbybees

Obsolete approveSignature calls

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java

Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/50.
@reviewbybees

[JENKINS-34564] Adjusted integration test to match modified behavior

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-38987 Follow-up] Expose the SCM API pronoun information

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/73. Amends #34.
@reviewbybees esp. @abayer

[JENKINS-35698] Integration test for params fallback behavior

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

Better behavior when SCMSource.fetch returns null

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Follows up https://github.com/jenkinsci/pipeline-plugin/pull/363.
@reviewbybees

[JENKINS-32179] Can enable test now

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStepTest.java

See [JENKINS-40906](https://issues.jenkins-ci.org/browse/JENKINS-40906) 
@reviewbybees

[FIXED JENKINS-40906] Resolve an SCM from an SCMSource and a list of candidate target branch names

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep/help-ignoreErrors.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep/help-source.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep/help-targets.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep/help.html

[JENKINS-40906] The missing configuration UI

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-33273] Use SCMFileSystem where available

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-40521](https://issues.jenkins-ci.org/browse/JENKINS-40521)
Downstream of https://github.com/jenkinsci/workflow-job-plugin/pull/37.
@reviewbybees

[JENKINS-40521] Mark orphaned branch projects as unbuildable

---

src/main/resources/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep/help.html

[JENKINS-41146](https://issues.jenkins-ci.org/browse/JENKINS-41146)
@reviewbybees

Emphasize that properties overwrites existing properties

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowMultiBranchProjectFactory.java

@reviewbybees esp. @jglick 
downstream of https://github.com/jenkinsci/branch-api-plugin/pull/82

Allow implementers to throw IOException

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep/help.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMVar/help.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/getting-started.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/getting-started.jelly

See [JENKINS-40558](https://issues.jenkins-ci.org/browse/JENKINS-40558)
@reviewbybees

[FIXED JENKINS-40558] Remove "pipeline script" and replace with "pipeline"

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

Added a Jenkinsfile

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

[JENKINS-34464](https://issues.jenkins-ci.org/browse/JENKINS-34464)
Downstream of https://github.com/jenkinsci/structs-plugin/pull/19
cc @reviewbybees

[JENKINS-34464] Test for Result working in Snippet Generator

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/getting-started.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/help-scriptPath.html
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/help-scriptPath.html
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

[JENKINS-34561](https://issues.jenkins-ci.org/browse/JENKINS-34561)
This is a re-worked version of #44, hopefully making @jglick happier (although I must confess I do not *completely* understand the issues he had with #44).
Of course I am happy to adjust this further. We could really use this feature, so I will definitely try to respond quickly to suggestions.
@dbut023 this is heavily based on your work, thanks for that.

[JENKINS-34561] Make Jenkinsfile filename configurable

---

src/main/resources/org/jenkinsci/plugins/workflow/multibranch/Messages_fr.properties

Implementing https://issues.jenkins-ci.org/browse/JENKINS-61489
Signed-off-by: Jean-Baptiste Le Duigou <jb.leduigou@gmail.com>

JENKINS-61489 Adding french locale

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchProperty.java

added symbol annotation to `DurabilityHintBranchProperty` to make databinding easier
cc @dwnusbaum @kshultzCB

adding symbol annotations to improve databinding

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchProperty.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchPropertyWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/GitDirectorySCMNavigator.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/NoTriggerBranchPropertyWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/RepairBranchPropertyTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ReplayActionTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMVarTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

A series of code cleanup changes for this repository. Most of these changes remove usages of deprecated functionality or otherwise fix IDE warnings. I kept each commit separate. Each commit message should be self-explanatory, but if anything is unclear I am happy to provide further explanation. Also, feel free to revert any specific cleanup commits that are unwanted.

Code cleanup

---

CHANGELOG.md

I am planning on releasing the plugin today.

Add release notes for 2.22

---

src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Fix test failure found in #99 due to miss wait for inactivity.

Fix test not waiting for no activity after indexing

---

.github/dependabot.yml
.github/release-drafter.yml
CHANGELOG.md

Add dependabot and release drafter

---

pom.xml

Fixes PCT on Java 11
jenkinsci/bom#401
cc @dwnusbaum @car-roll @bitwiseman

Bump subversion plugin dep

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowMultiBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchProperty.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyTrackerAction.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/GitDirectorySCMNavigator.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Add missing nullability annotations and replace JSR 305.
-----------

Add missing nullability annotations and replace JSR 305

---

pom.xml

Bump plugin parent POM from 4.19 to 4.31

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMVarTest.java

See https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/172.

[JENKINS-57023] Switch dep from `workflow-cps-global-lib` to `pipeline-groovy-lib`

---

src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java

Cleanup after #288. Analogous to https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/103.

Fix deprecations, avoid `@Inject`

---

pom.xml

Update to 2.462.1
